export type SeedKey
  = | 'morse'
    | 'morseWithEs'
    | 'k1'
    | 'k2'
    | 'k3'
    | 'k4Conventional'
    | 'k4DSTheory'
    | 'k1Plain'
    | 'k2Plain'
    | 'k3Plain'
    | 'CopperPlate'
    | 'CopperPlateWSolutions'

export const MORSE_WITHOUT_E = [
  'VIRTUALLY',
  'INVISIBLE',
  'SHADOW',
  'FORCES',
  'LUCID',
  'MEMORY',
  'RQ',
  'SOS',
  'DIGETAL',
  'INTERPRETATIU',
  'TISYOUR',
  'POSITION',
].join('\n')

export const MORSE_WITH_E = [
  'EEVIRTUALLYE',
  'EEEEEEINVISIBLE',
  'EESHADOWEE',
  'FORCESEEEEE',
  'LUCIDEEE',
  'MEMORYE',
  'RQ',
  'SOS',
  'EDIGETALEEE',
  'INTERPRETATIU',
  'TISYOUR',
  'POSITIONE',
].join('\n')

export const K1_PLAIN = 'BETWEENSUBTLESHADINGANDTHEABSENCEOFLIGHTLIESTHENUANCEOFIQLUSION'
export const K2_PLAIN = 'ITWASTOTALLYINVISIBLEHOWSTHATPOSSIBLE?THEYUSEDTHEEARTHSMAGNETICFIELDXTHEINFORMATIONWASGATHEREDANDTRANSMITTEDUNDERGRUUNDTOANUNKNOWNLOCATIONXDOESLANGLEYKNOWABOUTTHIS?THEYSHOULDITSBURIEDOUTTHERESOMEWHEREXWHOKNOWSTHEEXACTLOCATION?ONLYWWTHISWASHISLASTMESSAGEXTHIRTYEIGHTDEGREESFIFTYSEVENMINUTESSIXPOINTFIVESECONDSNORTHSEVENTYSEVENDEGREESEIGHTMINUTESFORTYFOURSECONDSWESTXLAYERTWO'
export const K3_PLAIN = 'SLOWLYDESPARATLYSLOWLYTHEREMAINSOFPASSAGEDEBRISTHATENCUMBEREDTHELOWERPARTOFTHEDOORWAYWASREMOVEDWITHTREMBLINGHANDSIMADEATINYBREACHINTHEUPPERLEFTHANDCORNERANDTHENWIDENINGTHEHOLEALITTLEIINSERTEDTHECANDLEANDPEEREDINTHEHOTAIRESCAPINGFROMTHECHAMBERCAUSEDTHEFLAMETOFLICKERBUTPRESENTLYDETAILSOFTHEROOMWITHINEMERGEDFROMTHEMISTXCANYOUSEEANYTHINGQ?'

export const K1_CIPHER = 'EMUFPHZLRFAXYUSDJKZLDKRNSHGNFIVJYQTQUXQBQVYUVLLTREVJYQTMKYRDMFD'
export const K2_CIPHER = 'VFPJUDEEHZWETZYVGWHKKQETGFQJNCEGGWHKK?DQMCPFQZDQMMIAGPFXHQRLGTIMVMZJANQLVKQEDAGDVFRPJUNGEUNAQZGZLECGYUXUEENJTBJLBQCRTBJDFHRRYIZETKZEMVDUFKSJHKFWHKUWQLSZFTIHHDDDUVH?DWKBFUFPWNTDFIYCUQZEREEVLDKFEZMOQQJLTTUGSYQPFEUNLAVIDXFLGGTEZ?FKZBSFDQVGOGIPUFXHHDRKFFHQNTGPUAECNUVPDJMQCLQUMUNEDFQELZZVRRGKFFVOEEXBDMVPNFQXEZLGREDNQFMPNZGLFLPMRJQYALMGNUVPDXVKPDQUMEBEDMHDAFMJGZNUPLGEWJLLAETG' // (left empty by default)
export const K3_CIPHER = 'ENDYAHROHNLSRHEOCPTEOIBIDYSHNAIACHTNREYULDSLLSLLNOHSNOSMRWXMNETPRNGATIHNRARPESLNNELEBLPIIACAEWMTWNDITEENRAHCTENEUDRETNHAEOETFOLSEDTIWENHAEIOYTEYQHEENCTAYCREIFTBRSPAMHHEWENATAMATEGYEERLBTEEFOASFIOTUETUAEOTOARMAEERTNRTIBSEDDNIAAHTTMSTEWPIEROAGRIEWFEBAECTDDHILCEIHSITEGOEAOSDDRYDLORITRKLMLEHAGTDHARDPNEOHMGFMFEUHEECDMRIPFEIMEHNLSSTTRTVDOHW?'

export const K4_CONVENTIONAL = 'OBKRUOXOGHULBSOLIFBBWFLRVQQPRNGKSSOTWTQSJQSSEKZZWATJKLUDIAWINFBNYPVTTMZFPKWGDKZXTJCDIGKUHUAUEKCAR'
export const COPPERPLATE_WSOLUTIONS = `${K1_PLAIN}${K2_PLAIN}${K3_PLAIN}${K4_CONVENTIONAL}`
export const COPPERPLATE = 'EMUFPHZLRFAXYUSDJKZLDKRNSHGNFIVJYQTQUXQBQVYUVLLTREVJYQTMKYRDMFDVFPJUDEEHZWETZYVGWHKKQETGFQJNCEGGWHKK?DQMCPFQZDQMMIAGPFXHQRLGTIMVMZJANQLVKQEDAGDVFRPJUNGEUNAQZGZLECGYUXUEENJTBJLBQCRTBJDFHRRYIZETKZEMVDUFKSJHKFWHKUWQLSZFTIHHDDDUVH?DWKBFUFPWNTDFIYCUQZEREEVLDKFEZMOQQJLTTUGSYQPFEUNLAVIDXFLGGTEZ?FKZBSFDQVGOGIPUFXHHDRKFFHQNTGPUAECNUVPDJMQCLQUMUNEDFQELZZVRRGKFFVOEEXBDMVPNFQXEZLGREDNQFMPNZGLFLPMRJQYALMGNUVPDXVKPDQUMEBEDMHDAFMJGZNUPLGEWJLLAETGENDYAHROHNLSRHEOCPTEOIBIDYSHNAIACHTNREYULDSLLSLLNOHSNOSMRWXMNETPRNGATIHNRARPESLNNELEBLPIIACAEWMTWNDITEENRAHCTENEUDRETNHAEOETFOLSEDTIWENHAEIOYTEYQHEENCTAYCREIFTBRSPAMHHEWENATAMATEGYEERLBTEEFOASFIOTUETUAEOTOARMAEERTNRTIBSEDDNIAAHTTMSTEWPIEROAGRIEWFEBAECTDDHILCEIHSITEGOEAOSDDRYDLORITRKLMLEHAGTDHARDPNEOHMGFMFEUHEECDMRIPFEIMEHNLSSTTRTVDOHW?OBKRUOXOGHULBSOLIFBBWFLRVQQPRNGKSSOTWTQSJQSSEKZZWATJKLUDIAWINFBNYPVTTMZFPKWGDKZXTJCDIGKUHUAUEKCAR'

export const textSeeds = {
  morse: MORSE_WITHOUT_E,
  morseWithEs: MORSE_WITH_E,
  k1: K1_CIPHER,
  k2: K2_CIPHER,
  k3: K3_CIPHER,
  k4Conventional: K4_CONVENTIONAL,
  k1Plain: K1_PLAIN,
  k2Plain: K2_PLAIN,
  k3Plain: K3_PLAIN,
  CopperPlateWSolutions: COPPERPLATE_WSOLUTIONS,
  CopperPlate: COPPERPLATE,
} as const

export const seedOptions = [
  { key: 'morse', label: 'Morse Code' },
  { key: 'morseWithEs', label: 'Morse Code with EEs' },
  { key: 'k1', label: 'K1 Encrypted' },
  { key: 'k2', label: 'K2 Encrypted' },
  { key: 'k3', label: 'K3 Encrypted' },
  { key: 'k4Conventional', label: 'K4 (conventional wisdom)' },
  { key: 'k1Plain', label: 'K1 Plaintext' },
  { key: 'k2Plain', label: 'K2 Plaintext' },
  { key: 'k3Plain', label: 'K3 Plaintext' },
  { key: 'CopperPlate', label: 'Full Copperplate' },
  { key: 'CopperPlateWSolutions', label: 'Copperplate with plaintext' },

]
